export const metadata = {
  title: 'blog',
  description: 'Generated by create next app',
}

export default function BlogLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <div>{children}</div>
}
